server:
  port: 8443
  tomcat:
    accesslog:
      enabled: true

management:
  endpoints:
    web:
      base-path: /get-out
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

info:
  app:
    version: @project.version@
    serviceName: @project.name@-${info.app.env}